config/routes.rb
Bookmarklove::Application.routes.draw do
  get "logout" => 'sessions#destroy', :as => 'logout'

  root :to => 'bookmarks#index'

  resources :users
  resources :sessions
  resources :bookmarks
  resources :imports
  resources :tags

  mount Resque::Server, :at => "/resque"
end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
  belongs_to :user
  acts_as_taggable_on :tags
  validates_presence_of :uri
  validates_uniqueness_of :uri, :scope => :user_id
  default_scope order('created_at desc')

  searchable do
    text :title, :boost => 5
    string :tag_list, :multiple => true
    text :raw_content
    integer :user_id
    date :created_month
    date :created_day
    time :created_at
  end

  def tags_json
    tags.map { |t| {:name => t.name, :id => t.name} }.to_json
  end

  def created_month
    Date.new created_at.year, created_at.month, 1
  end

  def created_day
    created_at.to_date
  end

  def generate_uri_digest
    self.uri_digest = Digest::MD5.hexdigest(self.uri)
  end

  def status
    case code
      when 200 then :ok
      when 301, 302 then :redirected
      when 404 then :gone
    end
  end
end

app/models/import.rb
class Import < ActiveRecord::Base
  belongs_to :user
  attr_accessible :file
  mount_uploader :file, ImportFileUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :nickname, :password, :password_confirmation
  has_secure_password
  acts_as_tagger
  validates_presence_of :password, :on => :create
  before_create { generate_token(:auth_token) }

  has_many :bookmarks, :dependent => :delete_all
  has_many :imports, :dependent => :delete_all

  def generate_token column
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def current_user
    @current_user ||= User.find_by_auth_token!(cookies[:auth_token]) if cookies[:auth_token]
  end
  helper_method :current_user

  def authenticate_user!
    if current_user.nil?
      redirect_to new_session_url, :alert => "You must first log in"
    end
  end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  respond_to :html, :json
  before_filter :authenticate_user!
  helper_method :bookmark

  def index
    @search = Bookmark.search(:include => [:tags]) do
      fulltext params[:q]
      with(:tag_list).all_of(params[:tags]) if params[:tags].present?
      with(:user_id, current_user.id)
      facet(:created_month, :sort => :index)
      with(:created_month, params[:month]) if params[:month].present?
      facet(:created_day, :sort => :index) if params[:month].present?
      with(:created_day, params[:day]) if params[:day].present?
      order_by :created_day, :desc
      paginate :page => params[:page], :per_page => 25
    end
    @bookmarks = @search.results
    @tags = current_user.bookmarks.tag_counts_on(:tags).order('count desc').limit(30)
    respond_with @bookmarks
  end

  def show
    respond_with bookmark
  end

  def new
    respond_with bookmark
  end

  def edit
    respond_with bookmark
  end

  def create
    if bookmark.save
      Resque.enqueue(CacheBookmark, bookmark.id)
    end
    respond_with bookmark
  end

  def update
    if bookmark.update_attributes params[:bookmark]
      Resque.enqueue(CacheBookmark, bookmark.id)
    end
    respond_with bookmark
  end

  def destroy
    bookmark.destroy
    respond_with bookmark
  end

  def bookmark
    @bookmark ||= if params[:id].present?
      current_user.bookmarks.find params[:id]
    else
      current_user.bookmarks.build params[:bookmark]
    end
  end
end

app/controllers/imports_controller.rb
class ImportsController < ApplicationController
  before_filter :authenticate_user!
  respond_to :html, :json

  def index
    @imports = current_user.imports.all
    respond_with @imports
  end

  def show
    @import = current_user.imports.find(params[:id])
    respond_with @import
  end

  def new
    @import = Import.new
    respond_with @import
  end

  def create
    @import = current_user.imports.build(params[:import])
    if @import.save
      Resque.enqueue ImportBookmark, @import.id
    end
    respond_with @import
  end

  def destroy
    @import = current_user.imports.find(params[:id])
    @import.destroy
    respond_with @import
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email params[:email]
    if user && user.authenticate(params[:password])
      if params[:remember_me]
        cookies.permanent[:auth_token] = user.auth_token
      else
        cookies[:auth_token] = user.auth_token
      end
      redirect_to root_url, :notice => "Logged in!"
    else
      flash.now.alert = "Invalid email or password"
      render :new
    end
  end

  def destroy
    cookies.delete(:auth_token)
    redirect_to root_url, :notice => "Logged out!"
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @tags = current_user.bookmarks.tag_counts_on(:tags)
                                  .where('name like ?', "#{params[:q]}%")
                                  .order('count desc')
                                  .limit(20)
    respond_to do |format|
      format.json { render :json => @tags.map(&:attributes) }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new params[:user]
    if @user.save
      redirect_to root_url, :notice => "Signed up!"
    else
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/imports_helper.rb
module ImportsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bookmarks/_form.html.erb
<%= simple_form_for(bookmark) do |f| %>
  <%= f.error_notification %>

  <div class="inputs">
    <%= f.input :uri %>
    <%= f.input :uri_digest %>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :tag_list, :input_html => {'data-pre' => bookmark.tags_json } %>
    <%= f.input :is_private %>
    <%= f.input :is_starred %>
    <%= f.input :is_unread %>
  </div>

  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/bookmarks/edit.html.erb
<h1>Editing bookmark</h1>

<%= render 'form' %>

<%= link_to 'Show', bookmark %> |
<%= link_to 'Back', bookmarks_path %>

app/views/bookmarks/index.html.erb
<%= form_tag bookmarks_path, :method => :get do %>
  <p>
    <%= search_field_tag :q, params[:q], :size => 120 %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>

<div id="facets">
  <h3>Bookmarklets</h3>


  <h3>Timeline</h3>
  <ul>
    <% for row in @search.facet(:created_month).rows.reverse! %>
      <li>
        <% if params[:month].blank? %>
          <%= link_to row.value.strftime("%Y %B"), :q => params[:q], :month => row.value %> (<%= row.count %>)
        <% else %>
          <strong><%= row.value.strftime("%Y %B") %></strong> (<%= link_to "✖", :month => nil %>)
        <% end %>
      </li>
    <% end %>
  </ul>

  <% if @search.facet(:created_day) %>
  <hr>
  <ul>
    <% for row in @search.facet(:created_day).rows.reverse! %>
      <li>
        <% if params[:day].blank? %>
          <%= link_to row.value.strftime('%e %B'), :day => row.value %>
              (<%= row.count %>)
        <% else %>
          <strong><%= row.value %></strong> (<%= link_to "✖", :day => nil %>)
        <% end %>
      </li>
    <% end %>
  </ul>

  <% end %>

  <h3>Tags</h3>
  <% tag_cloud(@tags, %w(css1 css2 css3 css4)) do |tag, css_class| %>
    <%= link_to tag.name, bookmarks_path(:tags => [tag.name]), :class => css_class %>
    <% if params[:tags].present? %>
      <% if params[:tags].include? tag.name %>
        <%= link_to '−', bookmarks_path(:tags => params[:tags] - [tag.name]) %>
      <% else %>
        <%= link_to '⊕', bookmarks_path(:tags => params[:tags] + [tag.name]),
                    :class => 'plus' %>
      <% end -%>
    <% end -%>
    •
  <% end %>
</div>

<h2>
<% if params[:month].present? %>
  <%= params[:month].to_date.strftime '%B %Y' %>
<% elsif params[:day].present? %>
  <%= params[:day].to_date.strftime '%e %B %Y' %>
<% elsif params[:tags].present? %>
  <%- params[:tags].each do |tag| %>
    <%= link_to tag, bookmarks_path(:tags => [tag]) %>
    <%= link_to '[−]', bookmarks_path(:tags => params[:tags] - [tag]),
                       :class => 'minus' %>
  <% end -%>
<% elsif params[:q].present? %>
  “<%= params[:q] %>”
<% end -%>
</h2>

<table>
  <tr>
    <th width="90%"></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @search.results.each do |bookmark| %>
  <tr>
    <td>
      <% if bookmark.is_starred %>
        <span class="full-star">★</span>
      <% else %>
        <span class="empty-star">☆</span>
      <% end -%>

      <%= bookmark.status %>
      <a href="<%= bookmark.uri %>"><%= truncate bookmark.title, :length => 70 %></a>
    </td>
    <td><%= link_to 'Show', bookmark %></td>
    <td><%= link_to 'Edit', edit_bookmark_path(bookmark) %></td>
    <td><%= link_to 'Destroy', bookmark, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<%= paginate @search %>

<br />

<%= link_to 'New Bookmark', new_bookmark_path %>

app/views/bookmarks/new.html.erb
<h1>New bookmark</h1>

<%= render 'form' %>

<%= link_to 'Back', bookmarks_path %>

app/views/bookmarks/show.html.erb
<p>
  <b>User:</b>
  <%= bookmark.user %>
</p>

<p>
  <b>Uri:</b>
  <%= bookmark.uri %>
</p>

<p>
  <b>Uri digest:</b>
  <%= bookmark.uri_digest %>
</p>

<p>
  <b>Title:</b>
  <%= bookmark.title %>
</p>

<p>
  <b>Description:</b>
  <%= bookmark.description %>
</p>

<p>
  <b>Is private:</b>
  <%= bookmark.is_private %>
</p>

<p>
  <b>Is starred:</b>
  <%= bookmark.is_starred %>
</p>

<p>
  <b>Is unread:</b>
  <%= bookmark.is_unread %>
</p>


<%= link_to 'Edit', edit_bookmark_path(bookmark) %> |
<%= link_to 'Back', bookmarks_path %>

app/views/imports/_form.html.erb
<%= simple_form_for(@import) do |f| %>
  <%= f.error_notification %>

  <div class="inputs">
    <%= f.input :file, :as => :file %>
  </div>

  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/imports/edit.html.erb
<h1>Editing import</h1>

<%= render 'form' %>

<%= link_to 'Show', @import %> |
<%= link_to 'Back', imports_path %>

app/views/imports/index.html.erb
<h1>Listing imports</h1>

<table>
  <tr>
    <th>User</th>
    <th>File</th>
    <th>Processed at</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @imports.each do |import| %>
  <tr>
    <td><%= import.user %></td>
    <td><%= import.file %></td>
    <td><%= import.processed_at %></td>
    <td><%= link_to 'Show', import %></td>
    <td><%= link_to 'Edit', edit_import_path(import) %></td>
    <td><%= link_to 'Destroy', import, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Import', new_import_path %>

app/views/imports/new.html.erb
<h1>New import</h1>
<%= form_tag({:action => :create}, :multipart => true) do %>
  <%= file_field_tag 'file' %>
  <%= submit_tag %>
<% end %>

app/views/imports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @import.user %>
</p>

<p>
  <b>File:</b>
  <%= @import.file %>
</p>

<p>
  <b>Processed at:</b>
  <%= @import.processed_at %>
</p>


<%= link_to 'Edit', edit_import_path(@import) %> |
<%= link_to 'Back', imports_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bookmarklove</title>
  <%= stylesheet_link_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller_name %>">
<div id="user_nav">
  <% if current_user %>
    <%= link_to "Import your bookmarks", new_import_path %>
    Logged in as <%= current_user.email %>.
    <%= link_to "Log out", logout_path %>
  <% else %>
    <%= link_to "Sign up", new_user_path %> or
    <%= link_to "log in", new_session_path %>
  <% end %>
</div>

<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>

<%= yield %>

<%= javascript_include_tag "application" %>
</body>
</html>

app/views/tags/index.html.erb
<h1>Tags#index</h1>
<% @tags.each do |tag| %>
  <%= tag.name %>
<% end %>

<%= paginate @tags %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p class="button"><%= f.submit %></p>
<% end %>